name: Flutter CI
on: 
  push:
    branches:
      - main
      - sprint-1
      - sprint-2
      - sprint-4
      - sprint-3
      - sprint-4
  

jobs:
  flutter_test:
    name: Run Flutter test and analyze
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with: 
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
